# Generated by Django 3.2.6 on 2021-08-24 18:01

from django.db import migrations, models
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80,null=False,blank=False)),
                ('address', models.CharField(max_length=150,null=False,blank=False)),
                ('phone_number', models.CharField(max_length=15, unique=True,blank=False,null=False)),
                ('email_address', models.CharField(max_length=70, unique=True)),
            ],
        ),
    ]
